big_title: '项目[一二三四五六七八九十\d+]{1,2}|第[一二三四五六七八九十\d+]{1,2}章'
单项选择题:
    shuoming: 【说明】每小题备选答案中，只有一个符合题意的正确答案。
    biaotiguanjianzi: '[一二三四五六七八九十\d].*选择题$|[一二三四五六七八九十\d].*单项选择题$|[一二三四五六七八九十\d].*单选题$|[一二三四五六七八九十\d].*选择题（单项选择）$|[一二三四五六七八九十\d].*选择题（单选）$'
    tihaoguanjianzi: '（[\d+]）|\d+．|\d+\.'
多项选择题:
    shuoming: 【说明】每小题备选答案中有多个正确选项，需从中选择2～4个符合题意的选项作为答案。
    biaotiguanjianzi: '[一二三四五六七八九十\d].*多项选择题$|[一二三四五六七八九十\d].*多选题$|[一二三四五六七八九十\d].*选择题（不定项选择）$|[一二三四五六七八九十\d].*选择题（不定项）$|[一二三四五六七八九十\d].*选择题（多选）$|[一二三四五六七八九十\d].*不定项选择题$|[一二三四五六七八九十\d].*不定项选择$'
    tihaoguanjianzi: '（[\d+]）|\d+．|\d+\.'
判断题:
    shuoming: 【说明】判断下列各项叙述是否正确。
    biaotiguanjianzi: '[一二三四五六七八九十\d].*判断题$'
    tihaoguanjianzi: '（[\d+]）|\d+．|\d+\.'
填空题:
    shuoming: 【说明】在空格处填写正确的答案。
    biaotiguanjianzi: '[一二三四五六七八九十\d].*填空题$'
    tihaoguanjianzi: '（[\d+]）|\d+．|\d+\.'
简答题:
    shuoming: 【说明】根据相关要求，完成下列题目。
    biaotiguanjianzi: '[一二三四五六七八九十\d].*简答题$|[一二三四五六七八九十\d].*编程题$|[一二三四五六七八九十\d].*操作题$|[一二三四五六七八九十\d].*实践题$|[一二三四五六七八九十\d].*问答题$|[一二三四五六七八九十\d].*改错题$|[一二三四五六七八九十\d].*计算题$|[一二三四五六七八九十\d].*设计题$|[一二三四五六七八九十\d].*综合应用题$|[一二三四五六七八九十\d].*思考题$|[一二三四五六七八九十\d].*练习题$|[一二三四五六七八九十\d].*名词解释|[一二三四五六七八九十\d].*分析题$|[一二三四五六七八九十\d].*技能实训|[一二三四五六七八九十\d].*任务操作题$|[一二三四五六七八九十\d].*解答题$|[一二三四五六七八九十\d].*实训题$|[一二三四五六七八九十\d].*案例分析|[一二三四五六七八九十\d].*案例思考|[一二三四五六七八九十\d].*实践操作|[一二三四五六七八九十\d].*识图题$'
    tihaoguanjianzi: '（[\d+]）|\d+．|\d+\.'
